package net.viralpatel.hibernate.mtm.anno.extra1;

// default package
// Generated 9 sept. 2014 17:20:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;

/**
 * EmployePosteId generated by hbm2java
 */
@Embeddable
public class EmployePosteId implements java.io.Serializable {

	/**
	 * 
//	 */
	private static final long serialVersionUID = 4901207298187996501L;
	
	private Employe employe;
	private Poste poste;
	
	/**
	 * You can also use association annotations in an embeddable object (ie @OneToOne, @ManyToOne, @OneToMany or @ManyToMany). 
	 * To override the association columns you can use @AssociationOverride.
	 * @return
	 */
	
	@ManyToOne
	public Employe getEmploye() {
		return employe;
	}
	public void setEmploye(Employe employe) {
		this.employe = employe;
	}
	
	@ManyToOne
	public Poste getPoste() {
		return poste;
	}
	public void setPoste(Poste poste) {
		this.poste = poste;
	}
	
	
	public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
 
        EmployePosteId that = (EmployePosteId) o;
 
        if (employe != null ? !employe.equals(that.employe) : that.employe != null) return false;
        if (poste != null ? !poste.equals(that.poste) : that.poste != null)
            return false;
 
        return true;
    }
 
    public int hashCode() {
        int result;
        result = (employe != null ? employe.hashCode() : 0);
        result = 31 * result + (poste != null ? poste.hashCode() : 0);
        return result;
    }
	
	
//	private long employeId;
//	private long posteId;
//
//	public EmployePosteId() {
//	}
//
//	public EmployePosteId(long employeId, long posteId) {
//		this.employeId = employeId;
//		this.posteId = posteId;
//	}
//
//	@Column(name = "employe_id", nullable = false)
//	public long getEmployeId() {
//		return this.employeId;
//	}
//
//	public void setEmployeId(long employeId) {
//		this.employeId = employeId;
//	}
//
//	@Column(name = "poste_id", nullable = false)
//	public long getPosteId() {
//		return this.posteId;
//	}
//
//	public void setPosteId(long posteId) {
//		this.posteId = posteId;
//	}
//
//	public boolean equals(Object other) {
//		if ((this == other))
//			return true;
//		if ((other == null))
//			return false;
//		if (!(other instanceof EmployePosteId))
//			return false;
//		EmployePosteId castOther = (EmployePosteId) other;
//
//		return (this.getEmployeId() == castOther.getEmployeId())
//				&& (this.getPosteId() == castOther.getPosteId());
//	}
//
//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result + (int) this.getEmployeId();
//		result = 37 * result + (int) this.getPosteId();
//		return result;
//	}

}
