package net.viralpatel.hibernate.mtm.anno.extra2;

// default package
// Generated 9 sept. 2014 17:20:58 by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Employe generated by hbm2java
 */
@Entity(name="net.viralpatel.hibernate.mtm.anno.extra2.Employe")
@Table(name = "employe", catalog = "hibernate_examples")
public class Employe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7023276647890699153L;
	private Long employeId;
	private String firstname;
	private String lastname;
	private Date birthDate;
	private String cellPhone;
	private Set<EmployePoste> employePostes = new HashSet<EmployePoste>(0);

	public Employe() {
	}
	
	public Employe(String firstname, String lastname) {
		this.firstname = firstname;
		this.lastname = lastname;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "employe_id", unique = true, nullable = false)
	public Long getEmployeId() {
		return this.employeId;
	}

	public void setEmployeId(Long employeId) {
		this.employeId = employeId;
	}

	

	

	@Column(name = "firstname", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birth_date", length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "cell_phone", length = 15)
	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "id.employe", cascade=CascadeType.ALL)
	public Set<EmployePoste> getEmployePostes() {
		return this.employePostes;
	}

	public void setEmployePostes(Set<EmployePoste> employePostes) {
		this.employePostes = employePostes;
	}

	
	public void addEmploye(EmployePoste employePoste) {
		
		if(employePostes == null){
			employePostes = new HashSet<EmployePoste>();
		}
		employePostes.add(employePoste);
		}
	
}
