package net.viralpatel.hibernate.mtm.xml.extra2;

// default package
// Generated 9 sept. 2014 10:41:35 by Hibernate Tools 3.6.0

/**
 * EmployePosteId generated by hbm2java
 */
public class EmployePosteId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6179019016233083097L;
	private long employeId;
	private long posteId;

	public EmployePosteId() {
	}

	public EmployePosteId(long employeId, long posteId) {
		this.employeId = employeId;
		this.posteId = posteId;
	}

	public long getEmployeId() {
		return this.employeId;
	}

	public void setEmployeId(long employeId) {
		this.employeId = employeId;
	}

	public long getPosteId() {
		return this.posteId;
	}

	public void setPosteId(long posteId) {
		this.posteId = posteId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployePosteId))
			return false;
		EmployePosteId castOther = (EmployePosteId) other;

		return (this.getEmployeId() == castOther.getEmployeId())
				&& (this.getPosteId() == castOther.getPosteId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEmployeId();
		result = 37 * result + (int) this.getPosteId();
		return result;
	}

}
