package net.viralpatel.hibernate.mtm.xml.extra1;

// Generated 9 sept. 2014 10:41:35 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employe generated by hbm2java
 */
public class Employe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6525260471230179312L;
	private Long employeId;
	private String firstname;
	private String lastname;
	private Date birthDate;
	private String cellPhone;
	private Set<EmployePoste> employePostes = new HashSet<EmployePoste>(0);

	public Employe() {
	}

	public Employe(String firstname, String lastname) {
		this.firstname = firstname;
		this.lastname = lastname;
	}

	public Long getEmployeId() {
		return this.employeId;
	}

	public void setEmployeId(Long employeId) {
		this.employeId = employeId;
	}

	

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	

	public Set<EmployePoste> getEmployePostes() {
		return this.employePostes;
	}

	public void setEmployePostes(Set<EmployePoste> employePostes) {
		this.employePostes = employePostes;
	}

	
	public void addEmploye(EmployePoste employePoste) {
		
		if(employePostes == null){
			employePostes = new HashSet<EmployePoste>();
		}
		employePostes.add(employePoste);
		}
}
