package net.viralpatel.hibernate.mtm.xml.extra1;

// Generated 9 sept. 2014 10:41:35 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import net.viralpatel.hibernate.mtm.xml.extra4.Employe;

/**
 * Poste generated by hbm2java
 */
public class Poste implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1838694168785557396L;
	private Long posteId;
	private Float remBase;
	private Character categorie;
	private String description;
	private Set<EmployePoste> employePostes = new HashSet<EmployePoste>(0);

	public Poste() {
	}
	
	
	public Poste(Float remBase, Character categorie, String description) {
		super();
		this.remBase = remBase;
		this.categorie = categorie;
		this.description = description;
	}

	public Poste(Float remBase, Character categorie, String description,
			Set<EmployePoste> employePostes) {
		this.remBase = remBase;
		this.categorie = categorie;
		this.description = description;
		this.employePostes = employePostes;
	}

	public Long getPosteId() {
		return this.posteId;
	}

	public void setPosteId(Long posteId) {
		this.posteId = posteId;
	}

	public Float getRemBase() {
		return this.remBase;
	}

	public void setRemBase(Float remBase) {
		this.remBase = remBase;
	}

	public Character getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Character categorie) {
		this.categorie = categorie;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<EmployePoste> getEmployePostes() {
		return this.employePostes;
	}

	public void setEmployePostes(Set<EmployePoste> employePostes) {
		this.employePostes = employePostes;
	}

	
	public void addEmploye(EmployePoste employePoste) {
		
		if(employePostes == null){
			employePostes = new HashSet<EmployePoste>();
		}
		employePostes.add(employePoste);
		}
}
