package net.viralpatel.hibernate.mtm.xml.extra4;

// Generated 9 sept. 2014 10:41:35 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * EmployePoste generated by hbm2java
 */
public class EmployePoste implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5831554546583479598L;
	
	private Long  employePostexmlId;
	private Employe employe;
	private Poste poste;
	private Float remuneration;
	private Date dateEmbauche;
	private Date dateDebut;
	private Date dateFin;

	public EmployePoste() {
	}

	public EmployePoste(Employe employe, Poste poste) {
		this.employe = employe;
		this.poste = poste;
	}

	public EmployePoste(Employe employe, Poste poste,
			Float remuneration, Date dateEmbauche, Date dateDebut, Date dateFin) {
		this.employe = employe;
		this.poste = poste;
		this.remuneration = remuneration;
		this.dateEmbauche = dateEmbauche;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
	}
	
	
	

	

	public Long getEmployePostexmlId() {
		return employePostexmlId;
	}

	public void setEmployePostexmlId(Long employePostexmlId) {
		this.employePostexmlId = employePostexmlId;
	}

	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
//		id.setEmployeId(employe.getEmployeId());
	}

	public Poste getPoste() {
		return this.poste;
	}

	public void setPoste(Poste poste) {
		this.poste = poste;
//		id.setPosteId(poste.getPosteId());
	}

	public Float getRemuneration() {
		return this.remuneration;
	}

	public void setRemuneration(Float remuneration) {
		this.remuneration = remuneration;
	}

	public Date getDateEmbauche() {
		return this.dateEmbauche;
	}

	public void setDateEmbauche(Date dateEmbauche) {
		this.dateEmbauche = dateEmbauche;
	}

	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	
	
}
